errors.kbuild: detect "undefined reference to" - add _find_script_target
In a log like the following:

	arm-linux-gnueabihf-ld: arch/arm/boot/compressed/atags_to_fdt.o: in function `atags_to_fdt':
	atags_to_fdt.c:(.text.atags_to_fdt+0x18): undefined reference to `stackleak_track_stack'
	make[3]: *** [arch/arm/boot/compressed/Makefile:152: arch/arm/boot/compressed/vmlinux] Error 1
	make[2]: *** [arch/arm/boot/Makefile:57: arch/arm/boot/compressed/vmlinux] Error 2
	make[1]: *** [arch/arm/Makefile:300: zImage] Error 2
	make: *** [Makefile:242: __sub-make] Error 2

Logspec would catch as error_str:
	"[arch/arm/boot/compressed/Makefile:152: arch/arm/boot/compressed/vmlinux] Error 1"

With target = vmlinux and script = arch/arm/boot/compressed/Makefile:152

This would be identified as KBuildCompilerError only if we are luck to
have some "vmlinux:" patten in the log, for instance:
	WARNING: modpost: vmlinux: gic_v3_dist_init: EXPORT_SYMBOL used for init symbol. Remove __init or EXPORT_SYMBOL.
Which is unrelated.

Fix this to get the script and the target from the line:
	arm-linux-gnueabihf-ld: arch/arm/boot/compressed/atags_to_fdt.o: in function `atags_to_fdt':

So the script is arm-linux-gnueabihf-ld and the target is arch/arm/boot/compressed/atags_to_fdt

Signed-off-by: Helen Koike <helen.koike@collabora.com>